### ISSUE TITLE
Read `numberOfNodesInSchain` from precompiled contract

### ISSUE THREAD

**Issue by olehnikolaiev** [skalenetwork/oracle-contract#72]
With latest changes in skaled the old way to get `numberOfNodesInSchain` doesn't work. Need to update oracle contract according updated precompileds (use `getConfigVariableUint256` precompiled contract for it)

**Comment by DmytroNazarenko** [comment]
skaled: 3.18.0-beta.0
oracle-contract: 1.0.0-develop.2
patch: `precompiledPatchTimestamp`

**Comment by OleksanderSalamatov** [comment]
Verified

skaled: 3.18.0-beta.1
oracle-contract: 1.0.0-develop.2

NodesReader contract was deployed and getNumberOfNodesInSchain returns correct value of nodes in schain

![image](https://github.com/skalenetwork/oracle-contract/assets/84843611/3afbfd30-ced4-48f3-83ca-e4fc412e8a08)
